name: Build pdoc documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc
          pip install -r requirements.txt

      - name: Build documentation with pdoc
        run: |
          pdoc SUILib --output-dir docs --docformat google
          touch docs/.nojekyll

      - name: Commit and push docs
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs
          git commit -m "Auto-update docs [skip ci]" || echo "No changes to commit"
          git push