name: Python Syntax Check

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check all Python files for syntax errors
        run: |
          find . -type f -name "*.py" ! -path "./venv/*" > pyfiles.txt
          while read file; do
            echo "Checking $file"
            python -m py_compile "$file"
          done < pyfiles.txt